### ISSUE TITLE
Solarcoind not staking

### ISSUE THREAD

**Issue by oliverlj** [Scalextrix/SolarCoin-Raspberry-Pi-Node#10]
Hello,

I have setup a node, sync the blockchain ( 2 weeks ...) and when i wan't to stake, it is not.

```
pi@rpi0:~ $ solarcoind getstakinginfo
{
    "Enabled" : true,
    "Staking" : false,
    "Stake" : 0.00000000,
    "Errors" : "",
    "Difficulty" : 0.42585613,
    "Search Interval" : 1,
    "Weight" : 0,
    "Net Stake Weight" : 33778229,
    "Expected Time" : -1,
    "Current Block Size" : 1000,
    "Current Block Tx" : 0,
    "Pooled Tx" : 0
}
```

**Comment by Scalextrix** [comment]
See how many blocks you have synced
> solarcoind getblockcount

that needs be upto the same height as https://chainz.cryptoid.info/slr/

**Comment by oliverlj** [comment]
Hi, after 12h, the staking if true, so it is good now.
Thanks.
