### ISSUE TITLE
Raspi-4 GUI - no proper startup/ shutdown

### ISSUE THREAD

**Issue by phillumene** [Scalextrix/SolarCoin-Raspberry-Pi-Node#11]
Hello all,

I installed the solarcoin wallet as described on my raspberry pi 4 running raspian buster. I allowed it to synchronize with the network slowly and it is staking.

Still I observe this strange behaviour:
- When starting, the program still tries to download the bootstrap file. After 30 seconds it stops trying to download it and I can sign-in. Under Windows 10 it did the same in the beginning, but once the program was synchronized with the network, it never appeared again.

- When shutting the program down, after 10 seconds it starts again. I can kill that again, but it keeps restarting, unless I restart the whole device.

Does anyone of you has a clue how I can get rid of this annoying behaviour?

**Comment by Scalextrix** [comment]
Make sure your data directory has a file "bootstrap.zip", it doesn't even need to be the real one, just an empty file with that name should cure the issue

**Comment by phillumene** [comment]
home/pi/.solarcoin/bootstrap.zip

I added a dummy file as recommended and it solved both issues. Great, thanks!
