### ISSUE TITLE
How does the Solarcoin code get updated?

### ISSUE THREAD

**Issue by billraff** [Scalextrix/SolarCoin-Raspberry-Pi-Node#2]
I followed these instructions to successfully set up a node on my Raspberry Pi. I can update the system periodically that the node runs on but wonder about the node code itself. How does it get updated?
Thanks for pointing me in the right direction.

**Comment by Scalextrix** [comment]
You can:

> sudo systemctl stop solarcoind.service 

> cd solarcoin

>git pull

Then it would show if there were any incremental updates to re-compile, if there were you basically recompile from around step 5 with:

> cd src

> make -f makefile.unix -e PIE=1

> strip solarcoind

> sudo install -m 755 solarcoind /usr/local/bin/solarcoind

> sudo systemctl start solarcoind.service

However there is a major new version of solarcoin core coming soon, and the installation process will be different, at that time a new guide may be required.
