### ISSUE TITLE
hardening-includes

### ISSUE THREAD

**Issue by jegb** [Scalextrix/SolarCoin-Raspberry-Pi-Node#3]
I got an error that hardening-includes could not be found, then found this [on hardening in debian](https://wiki.debian.org/Hardening#hardening-includes). Should this be removed from dependencies?

**Comment by Scalextrix** [comment]
The removal was the case with Raspbian Stretch, Jessie still has hardening-includes I believe and the guide is based on that earlier release.
As hardening-includes is just a method to check the executable it can be removed, providing the PIE=1 environmental variable is passed to make.

**Comment by jegb** [comment]
thanks, closing
