### ISSUE TITLE
solarcoind

### ISSUE THREAD

**Issue by jegb** [Scalextrix/SolarCoin-Raspberry-Pi-Node#5]
Using jessie, at the end, running solarcoind I got:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
```

any hints?

**Comment by jegb** [comment]
solved:
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen

**Comment by Scalextrix** [comment]
Cool, I didnt have time to look, glad you are up and running
