### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by jegb** [Scalextrix/SolarCoin-Raspberry-Pi-Node#6]
`Traceback (most recent call last):
  File "./solarcoin_RPC.py", line 191, in <module>
    instruct_wallet(ip_choice, command, command_chooser)
  File "./solarcoin_RPC.py", line 115, in instruct_wallet
    answer = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

I am not sure if I have this set up correctly. This is trying the RPC python code you shared

**Comment by Scalextrix** [comment]
Were you issuing a specific command when you got the error, Im just using it now.

Have you installed the 'requests' module?

**Comment by jegb** [comment]
my problem comes perhaps due to the port closed on the router, you have that in the instructions but I noticed afterwards.

**Comment by Scalextrix** [comment]
You only need to open a port on the router if you want your solarcoind to 'listen' for incoming connections, that wont effect using the RPC.
However, some other things to check that I should have added to the README.md, your solarcoin.conf file must have:
rpcuser=(insert a username if one isnt already present)
rpcpassword=(insert a password if one isnt already present)
daemon=1
server=1
