### ISSUE TITLE
SolarCoin: Error loading blkindex.dat

### ISSUE THREAD

**Issue by jegb** [Scalextrix/SolarCoin-Raspberry-Pi-Node#7]
I got this error starting the service.
debug.log reports this:
```
SolarCoin Version v2.1.8.0 (2016-11-23 11:34:53 -0700)
Using OpenSSL version OpenSSL 1.0.1t  3 May 2016
Startup time: 12/16/17 09:29:47
Default data directory /home/pi/.solarcoin
Used data directory /home/pi/.solarcoin
dbenv.open LogDir=/home/pi/.solarcoin/database ErrorFile=/home/pi/.solarcoin/db.log
Bound to [::]:18188
Bound to 0.0.0.0:18188
Loading block index...
Opening LevelDB in /home/pi/.solarcoin/txleveldb
Transaction index version is 70508
Opened LevelDB successfully
```

any idea what may be the source of this?

**Comment by Scalextrix** [comment]
That doesnt seem to show an error, this is my debug.log 
>SolarCoin Version v2.1.8.0 (2016-11-23 11:34:53 -0700)
Using OpenSSL version OpenSSL 1.0.1t  3 May 2016
Startup time: 12/16/17 11:20:57
Default data directory /home/pi/.solarcoin
Used data directory /home/pi/.solarcoin
dbenv.open LogDir=/home/pi/.solarcoin/database ErrorFile=/home/pi/.solarcoin/db.log
Bound to [::]:18188
Bound to 0.0.0.0:18188
Loading block index...
Opening LevelDB in /home/pi/.solarcoin/txleveldb
Transaction index version is 70508
Opened LevelDB successfully

After its done loading blocks the debug.log should get longer.  I guess if thats not happening then there is your problem.  

Did you have a sudden power loss on your Pi, or did the daemon get shutdown improperly?  I never saw the blocks get corrupted before

**Comment by jegb** [comment]
there may have been one of these 2 things:
-shutdown (power cut) without stopping solarcoind 
-network ip change (router ip address changed while mining)

is there anyway to restart the syncing from scratch deleting this blkindex.dat file? where is it located?

**Comment by Scalextrix** [comment]
EDIT: I didnt read the IP Address issue properly, if thats the case just do 
> ifconfig

 see what your new LAN IP is and reconfigure your Pi or router... otherwise, probably some kind of bad shutdown then.

So if its the latter, login to your Pi, make sure you have a wallet.dat backup, then to delete the blockchain files:

> cd .solarcoin

> rm -r txleveldb

> rm -r database

> rm blk0001.dat

Then if you restart the daemon you should be syncing from 0 again... thats painful, sorry :(

**Comment by jegb** [comment]
thanks that made the server start, 
pi@raspberrypi:~/.solarcoin $ solarcoind getinfo
{
    "version" : "v2.1.8.0",
    "protocolversion" : 70005,
    "walletversion" : 60001,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 0,
    "timeoffset" : 0,
    "connections" : 0,
    "proxy" : "",
    "ip" : "0.0.0.0",
    "difficulty" : {
        "proof-of-work" : 0.00024414,
        "proof-of-stake" : 0.00024414
    },
    "coinsupply" : 33017974,
    "blocksperhour" : 0,
    "testnet" : false,
    "keypoololdest" : 1512131794,
    "keypoolsize" : 101,
    "paytxfee" : 0.00010000,
    "mininput" : 0.00001000,
    "errors" : ""
}

I am not sure why I can not see anymore the ip address, I used to see it.

**Comment by Scalextrix** [comment]
Check if your Pi has connection to the local network & internet
