### ISSUE TITLE
Package hardening-includes is not available

### ISSUE THREAD

**Issue by wast** [Scalextrix/SolarCoin-Raspberry-Pi-Node#8]
Tutorial says:

b- Install Required Dependencies with next commands:

`sudo apt-get install autoconf libevent-dev libtool libssl-dev libboost-all-dev libminiupnpc-dev libdb-dev libdb4.8++ libdb5.3++-dev git hardening-includes rng-tools -y`

Response for package hardening-includes:

Package hardening-includes is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'hardening-includes' has no installation candidate

**Comment by Scalextrix** [comment]
Are you using Raspbian Jessie or Stretch.  The guide notes it will only work in Jessie. 

hardening-includes is not essential and can be removed, but the compiler will fail later if you are on Stretch anyway.

**Comment by wast** [comment]
OK. It's Stretch, and later I found out it won't work on Raspberry Pi Zero W neither.
:(
Closing...
